name: infrastructure
services:
  # nginx:
  #   image: "nginx:1.25.4"
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   networks:
  #     - external_net
  #     - internal_net
  #   volumes:
  #     - ./conf:/etc/nginx/conf.d
  #     - ./html:/usr/share/nginx/html
  #   depends_on:
  #     - flask

  # flask:
  #   build: ./python/
  #   networks:
  #     internal_net:
  #       aliases:
  #         - flask
  #   volumes:
  #     - ./app:/app
  #   deploy: 
  #     replicas: 2
  #   restart: on-failure
  #   command: python app.py



  ca:
    build: ./certificate/
    container_name: ca-cert
    env_file: .env_certs
    volumes:
      # - ./pki_conf:/pki
      - ./pki:/pki
    # networks:
    #   - default
    # command: sleep infinity
      # - openssl genrsa -out ca.key 4096
    

# volumes:
#   pki:

networks:
  external_net:
    driver: bridge
  internal_net:
    name: internal_net
    driver: bridge










# configs:
#   ca-cart:
#     content: | 
#       ca_req.conf
#       [ req ]
#       default_bits = 4096
#       encrypt_key = no
#       default_md = sha256
#       prompt = no
#       utf8 = yes
#       distinguished_name = ca_distinguished_name
#       req_extensions = ca_extensions

#       [ ca_distinguished_name ]
#       C = RU
#       ST = Moscow State
#       L = Moscow
#       O = Bauman Moscow State Technical University
#       CN = Dychakovskaya Anastasia

#       [ ca_extensions ]
#       basicConstraints = critical,CA:TRUE
#       keyUsage = critical,keyCertSign,cRLSign
#       subjectKeyIdentifier = hash