name: infrastructure
services:
  nginx:
    image: "nginx:1.25.4"
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - external_net
      - internal_net
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
    depends_on:
      - flask

  flask:
    build: .
    networks:
      internal_net:
        aliases:
          - flask
    volumes:
      - ./app:/app
    deploy: 
      replicas: 2
    restart: on-failure
    command: python app.py

networks:
  external_net:
    driver: bridge
  internal_net:
    name: internal_net
    driver: bridge